In [1]:
import cv2
import numpy as np



In [2]:
img=cv2.imread("dog0.jpg") #yükler #,cv2.IMREAD_GRAYSCALE görüntüyü siyah beyaz alır ya da direkt 0 vererekte alabiliriz.
img=cv2.resize(img,(200,200)) #img dosyasına yeni size atar.
cv2.namedWindow("image",cv2.WINDOW_NORMAL) #size'ını istediğimiz gibi ayarlarız
cv2.imshow("image",img) #değişkenin ismini image yaptık.
cv2.imwrite("copy.jpg",img) #kopyasını kaydeder
cv2.waitKey(0) # klavyeden herhangi bir tuşa basana kadar bekletir.

cv2.destroyAllWindows() #açık olan tüm pencerelerin otomatik olarak kapanması
########################################

In [3]:
# Her video frame'lerden oluşur.
cap=cv2.VideoCapture(0,cv2.CAP_DSHOW) # 0 yazarsak pc kamerası kabul edilir.
file="C:/Users/Ertuğrul/Desktop/Veri Bilimi ve Makine Öğrenmesi (BTK)/OPENCV/video/1.avi"
codec=cv2.VideoWriter_fourcc("W","M","V","2")
framerate=30
resolution=(640,480)
output=cv2.VideoWriter(file,codec,framerate,resolution)
while True:
    ret,frame=cap.read() #ret True veya false döndürür,video bittiği zaman False döndürücek ve sonlandırma işlemi yapacağız. frame ise anlık fotoğrafları yakalar.
    frame=cv2.flip(frame,1) # sağ sol kamera tersliğini engeller
    output.write(frame)
    cv2.imshow("webcab",frame)
    if cv2.waitKey(1) & 0xFF ==ord("q"):
        break
    cv2.waitKey(30) #burayı 1000 yaparsak saniyede 1 frame yakalamaya çalışır
output.release()
cap.release()
cv2.destroyAllWindows()

In [11]:
canvas=np.zeros((512,512,3),dtype=np.uint8) +100 #canvas=tuval, boş bir tuval oluşturuyoruz.
#uint8, bu dizinin veri türünü 8 bitlik tam sayıya ayarlar. bu da 0-255 arası
#print(canvas)                    
cv2.imshow("image",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
img=np.zeros((20,20,3),dtype=np.uint8)+255
img[0,0]=(0,0,0)
img[0,1]=(50,0,0)
img[0,2]=(100,0,0)
img[0,3]=(150,0,0)
img[0,4]=(200,0,0)
"""
#siyah beyaz içinde bunu uygulayabiliriz.
img=np.zeros((20,20),dtype=np.uint8)+255
img[0,0]=0
img[0,1]=50
img[0,2]=100
img[0,3]=150
img[0,4]=200

"""
#görüntü küçültürken INTER_AREA, büyütürken INTER_CUBIC veya INTER_LINEAR
img=cv2.resize(img,(500,500),interpolation=cv2.INTER_LINEAR)
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [53]:
#şekil işlemleri ve üzerlerine text eklemesi
canvas=np.zeros((500,500,3),np.uint8)+255
"""
cv2.line(canvas,(100,100),(300,300),(0,255,0),thickness=4)
"""
f1=cv2.FONT_HERSHEY_SIMPLEX
f2=cv2.FONT_HERSHEY_COMPLEX
f3=cv2.CAP_ARAVIS

cv2.putText(canvas,"Rectangle",(170,150),f1,1.5,(255,0,0),2,cv2.LINE_AA)
cv2.rectangle(canvas,(200,175),(300,250),(255,0,0),4)

cv2.putText(canvas,"Circle",(40,200),f2,1,(0,255,0),1,cv2.LINE_AA)
cv2.circle(canvas,(100,100),(60),(0,255,0),4)

u1=(300,300)
u2=(300,400)
u3=(350,350)

cv2.putText(canvas,"Triangle",(275,290),f3,1,(0,0,255),1,cv2.LINE_AA)
cv2.line(canvas,u1,u2,(0,0,255),4)
cv2.line(canvas,u2,u3,(0,0,255),4)
cv2.line(canvas,u1,u3,(0,0,255),4)

cv2.imshow("image",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [2]:
#TrackBar

def fonk(x):
    pass

img=np.zeros((512,512,3),np.uint8)
cv2.namedWindow("Image")

cv2.createTrackbar("r","Image",0,255,fonk)
cv2.createTrackbar("g","Image",0,255,fonk)
cv2.createTrackbar("b","Image",0,255,fonk)

switch="0: OFF, 1: ON"
cv2.createTrackbar(switch,"Image",0,1,fonk)

while True:
    cv2.imshow("Image",img)
    if cv2.waitKey(1) & 0xFF==ord("q"):
        break

    r=cv2.getTrackbarPos("r","Image")
    g=cv2.getTrackbarPos("g","Image")
    b=cv2.getTrackbarPos("b","Image")

    s=cv2.getTrackbarPos(switch,"Image")
    
    if s==0:
        img[:]=[0,0,0]
    if s==1:
        img[:]=[b,g,r]

cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
#Pixel işlemleri
img=cv2.imread("dog0.jpg")
print(img.shape)
"""
blue=img[200,300,0]
print("blue: ",blue)

green=img[200,300,1]
print("green: ",green)

red=img[200,300,2]
print("red: ",red)
"""
img.itemset((150,150,0),200) #blue değerini 200 yap dedik.

print(img[150,150])
cv2.imshow("dog",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


(375, 499, 3)
[200  49  80]


In [14]:
#Roi işlemi
img=cv2.imread("car.jpg")
print(img.shape) #596,900
roi=img[300:360,530:670]
cv2.imshow("image",img)
cv2.imshow("plaka",roi)

cv2.waitKey(0)
cv2.destroyAllWindows()

(596, 900, 3)


In [18]:
#resim birleştirme

circle=np.zeros((512,512,3),np.uint8)+255
cv2.circle(circle,(256,256),50,(0,255,0),-1)

rectangle=np.zeros((512,512,3),np.uint8)+255
cv2.rectangle(rectangle,(150,150),(350,350),(0,0,255),-1)

cv2.imshow("circle",circle)
cv2.imshow("rectangle",rectangle)

# A n B
sum=cv2.add(rectangle,circle)
cv2.imshow("A n B",sum)

# A U B
weight=cv2.addWeighted(circle,0.5,rectangle,0.5,0)
cv2.imshow("A U B",weight)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [19]:
#Renk değişimi

img=cv2.imread("car.jpg")
img1=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
img2=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
img3=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)


cv2.imshow("BGR-car",img)
cv2.imshow("RGB-car",img1)
cv2.imshow("HSV-car",img2)
cv2.imshow("GRAY-car",img3)

cv2.waitKey(0)
cv2.destroyAllWindows()



In [22]:
#Video renk değişimi
cap=cv2.VideoCapture("firevideo.mp4")

while True:
    ret,frame=cap.read()

    if ret == 0:
        break
    
    frame=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
    cv2.imshow("video",frame)

    if cv2.waitKey(20) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

In [2]:
cap=cv2.VideoCapture(0)
def fonk(x):
    pass
cv2.namedWindow("bar")
cv2.resizeWindow("bar",600,600)

cv2.createTrackbar("alt-h","bar",0,180,fonk)
cv2.createTrackbar("alt-s","bar",0,255,fonk)
cv2.createTrackbar("alt-v","bar",0,255,fonk)

cv2.createTrackbar("ust-h","bar",0,180,fonk)
cv2.createTrackbar("ust-s","bar",0,255,fonk)
cv2.createTrackbar("ust-v","bar",0,255,fonk)

cv2.setTrackbarPos("ust-h","bar",150)
cv2.setTrackbarPos("ust-s","bar",200)
cv2.setTrackbarPos("ust-v","bar",200)


while True:
    ret,frame=cap.read()
    frame=cv2.flip(frame,1)
    frame_hsv=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)

    alt_h=cv2.getTrackbarPos("alt-h","bar")
    alt_s=cv2.getTrackbarPos("alt-s","bar")
    alt_v=cv2.getTrackbarPos("alt-v","bar")

    ust_h=cv2.getTrackbarPos("ust-h","bar")
    ust_s=cv2.getTrackbarPos("ust-s","bar")
    ust_v=cv2.getTrackbarPos("ust-v","bar")

    alt_renk=np.array([alt_h,alt_s,alt_v])
    ust_renk=np.array([ust_h,ust_s,ust_v])

    mask=cv2.inRange(frame_hsv,alt_renk,ust_renk)

    cv2.imshow("m",mask)
    cv2.imshow("f",frame)
    if cv2.waitKey(20) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

In [3]:
#filtreleme işlemleri
img1=cv2.imread("car.jpg")

blr=cv2.blur(img1,(15,15))
gb=cv2.GaussianBlur(img1,(15,15),cv2.BORDER_DEFAULT)
mb=cv2.medianBlur(img1,9)
b=cv2.bilateralFilter(img1,9,75,75)

cv2.imshow("orj",img1)
cv2.imshow("gb",gb)
cv2.imshow("mb",mb)
cv2.imshow("b",b)
cv2.imshow("blr",blr)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
img1=cv2.imread("1bit1.png")
img2=cv2.imread("2bit2.png")
bit_and=cv2.bitwise_and(img1,img2)
bit_or=cv2.bitwise_or(img1,img2)
bit_xor=cv2.bitwise_xor(img1,img2)
bit_not1=cv2.bitwise_not(img1)
bit_not2=cv2.bitwise_not(img2)
cv2.imshow("1",img1)
cv2.imshow("2",img2)
cv2.imshow("and",bit_and)
cv2.imshow("not1",bit_not1)
cv2.imshow("not2",bit_not2)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
import cv2
img=cv2.imread("car.jpg",0) #grayscale olarak yükler.

sat,sut=img.shape
print(sat)
print(sut)
m=cv2.getRotationMatrix2D((sut/2,sat/2),180,1) #döndürme matrisini oluşturur.
d=cv2.warpAffine(img,m,(sut,sat)) #döndürme dönüşümünü uygular.

cv2.imshow("image",d)
cv2.waitKey(0)
cv2.destroyAllWindows()

596
900


In [13]:
# köşe tespiti
import numpy as np
img=cv2.imread("ucgen.png")
gri=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gri=np.float32(gri)
corner=cv2.goodFeaturesToTrack(gri,3,0.01,10)

corner=np.int0(corner) #7.3==> 7, 7.9==> 7 yapar
for c in corner:
    x,y=c.ravel() #düzleştirme işlemi
    cv2.circle(img,(x,y),3,(255,0,0),-1)

import numpy as np
img=cv2.imread("opencv.png")
gri=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gri=np.float32(gri)
corner=cv2.goodFeaturesToTrack(gri,20,0.01,10)

corner=np.int0(corner) 
for c in corner:
    x,y=c.ravel() 
    cv2.circle(img,(x,y),3,(255,0,0),-1)
cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [15]:
# canny kenar tespiti
cap=cv2.VideoCapture(0)

while True:
    ret,frame=cap.read()
    frame=cv2.flip(frame,1)
    kenar=cv2.Canny(frame,100,200) #buradan hassasiyeti ayarlıyoruz.

    cv2.imshow("f",frame)
    cv2.imshow("k",kenar)

    if cv2.waitKey(5) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

In [16]:
#contour belirleme
img=cv2.imread("insan-vazo.jpg")
gri=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

ret,thresh=cv2.threshold(gri,100,200,cv2.THRESH_BINARY)
cont,a=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE) #diğer 2 parametre default
cv2.drawContours(img,cont,-1,(0,255,0),2) #3.parametre -1 olunca sağ sol ikisini de verir. -1<x<1 

cv2.imshow("1",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
#Ağırlık merkezi bulma
img=cv2.imread("ucgen.png")

gri=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ai,thresh=cv2.threshold(gri,100,200,cv2.THRESH_BINARY)
m=cv2.moments(thresh)
print(m)
x=int(m["m10"]/m["m00"])
y=int(m["m01"]/m["m00"])

cv2.circle(img,(x,y),3,(0,255,0),-1)
cv2.imshow("s",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

{'m00': 57334400.0, 'm10': 21304680600.0, 'm01': 12315971600.0, 'm20': 10839537931400.0, 'm11': 4562875654800.0, 'm02': 3646729752000.0, 'm30': 6189763612794600.0, 'm21': 2324882051309600.0, 'm12': 1348097292312800.0, 'm03': 1220804851809200.0, 'mu20': 2923009364466.0757, 'mu11': -13571316244.79996, 'mu02': 1001142522483.2253, 'mu30': -10361535137168.352, 'mu21': 6532575176405.208, 'mu12': -1147222498309.4087, 'mu03': 7343024225435.61, 'nu20': 0.000889200427232929, 'nu11': -4.128491803581209e-06, 'nu02': 0.00030455474058179946, 'nu30': -4.1628036247731647e-07, 'nu21': 2.6244979400682176e-07, 'nu12': -4.609029367909712e-08, 'nu03': 2.950100294771009e-07}


cvtColor ile BG2GRAY kullanarak işlem yapmamızın sebebi, genellikle işlem yapılacak görüntü için daha uygun ve daha az işlem gücü gerektiren bir renk uzayı olmasıdır.Gri tonlamalı görüntü, yalnızca bir renk kanalı içerir ve gri tonlarla ifade edilir, bu nedenle işlem yaparken daha basit ve hızlı olabilir.

Görüntü işleme uygulamalarında, şekillerin çevrelerini belirlemek ve konturlarını bulmak için genellikle ikili(binary) görüntüler kullanılır.İkili görüntülerde pikseller yalnızca iki değer alır: siyah(0), veya beyaz(1 veya 255).İkili görüntü, genellikle temel şekil analizi ve nesne tespiti için ön işlem adımı olarak kullanılır ve kontur tespiti için oldukça yaygın bir yaklaşımdır. threshold fonksiyonunda iki parametre olarak verilen değerler şunlardır:
* ret, eşiklemede kullanılan eşik değerini döndüren bir değişkendir. Eğer fonksiyon başarılı bir şekilde çalışırsa True döndürür ve ret kullanılarak eşik değeri elde edilebilir.
* thresh, threshold fonksiyonu sonucu elde edilen ikili görüntüdür.

findContours(), ikili bir görüntü üzerindeki nesnelerin konturlarını(sınırlarını) bulmak için kullanılır. ilk parametresi görüntü (ikili görüntü) üzerinde konturları bulur. İkinci parametre kontur bulma yöntemini ve konturun içinde bulunma ilişkisini belirler. 3.parametre kontur yaklaşım yöntemini belirler.
* contours değişkeni, tespit edilen konturların koordinatlarını içeren bir liste olarak döner.
* hierarchy değişkeni ise kontur hiyerarşisini içeren bir dizidir. Bu hiyerarşi, konturların iç içe geçmiş durumlarını ve üst-alt ilişkilerini ifade eder.Bu özel bir yapıdır ve çeşitli amaçlar için kullanılabilir.


In [16]:
#convex hull ile dış bükey tespit
import numpy as np
import cv2


img=cv2.imread("convexhull.png")

gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ret,thresh=cv2.threshold(gray,75,200,cv2.THRESH_BINARY) #görüntüyü belirli bir eşik değeriyle ikili bir görüntüye dönüştürmek için cv2.threshold
contur,hierarchy=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

h=[]

for i in range(len(contur)):
    h.append(cv2.convexHull(contur[i],False))

z=np.zeros((thresh.shape[0],thresh.shape[1],3),np.uint8) #shape[0],shape[1] ikili görüntünün yükseklik ve genişliğini ifade eder.

for i in range(len(contur)):
    cv2.drawContours(z,contur,i,(255,0,0),3,0)
    cv2.drawContours(z,h,i,(0,255,0),1,0)
# for i in range(len(h)):    
#     cv2.drawContours(z,h,i,(0,255,0),1,0)

#çevre ve alanı bulmak istesek,
cnt=h[0]
M=cv2.moments(cnt) 
print(M)

alan=cv2.contourArea(cnt)
print(alan)
print(M["m00"]) #m00 değeri de aynı zamanda alanı verir.

cevre=cv2.arcLength(cnt,True) #Kapalı bir şekilse True, değilse False
print(cevre)

# cv2.imshow("image",z)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

{'m00': 72488.0, 'm10': 26023192.0, 'm01': 16128580.0, 'm20': 9883401725.333332, 'm11': 5790160220.0, 'm02': 3916719941.333333, 'm30': 3936633641880.0, 'm21': 2199056883886.6665, 'm12': 1406102458938.6667, 'm03': 1017479533590.0, 'mu20': 541075797.3333321, 'mu11': 0.0, 'mu02': 328110891.333333, 'mu30': 0.00146484375, 'mu21': 0.0001220703125, 'mu12': 0.0001983642578125, 'mu03': 0.000244140625, 'nu20': 0.10297359458924511, 'nu11': 0.0, 'nu02': 0.06244366883714079, 'nu30': 1.0354425528935233e-15, 'nu21': 8.628687940779361e-17, 'nu12': 1.4021617903766462e-16, 'nu03': 1.7257375881558723e-16}
72488.0
72488.0
1013.6888427734375


In [27]:
#Şekil algılama
img=cv2.imread("sekiller.png")
font=cv2.FONT_HERSHEY_SIMPLEX
gri=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

a, thresh=cv2.threshold(gri,200,300,cv2.THRESH_BINARY)
kontur,b=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

for i in kontur:
    e=0.01*cv2.arcLength(i,True)
    approx=cv2.approxPolyDP(i,e,True)
    cv2.drawContours(img,[approx],0,5)

    x=approx.ravel()[0]
    y=approx.ravel()[1]
    print(len(approx))

    if len(approx)==3:
        cv2.putText(img,"ucgen",(x,y),font,1,1,(0))
    elif len(approx)==4:
        cv2.putText(img,"dortgen",(x,y),font,1,1,(0))
    elif len(approx)==5:
        cv2.putText(img,"besgen",(x,y),font,1,1,(0))
    elif len(approx)==6:
        cv2.putText(img,"altigen",(x,y),font,1,1,(0))
    else:
        cv2.putText(img,"cember",(x,y),font,1,1,(0))

cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

4
16
15
6
6
3
3
4
4


In [4]:
#Video'dan background çıkartma
import cv2
import numpy as np
cap=cv2.VideoCapture("arabavideo.mp4")
sub=cv2.createBackgroundSubtractorMOG2(history=150,varThreshold=75,detectShadows=True)

while True:
    a,frame=cap.read()
    m=sub.apply(frame)
    if cv2.waitKey(20) & 0xFF==ord("q"):
        break

    cv2.imshow("frame",frame)
    cv2.imshow("mask",m)

cap.release()
cv2.destroyAllWindows()

In [5]:
#Hough Line Transform Resimden çizgi tespiti

img=cv2.imread("cizgi.png")
gri=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
kenar=cv2.Canny(gri,100,250)
cizgi=cv2.HoughLinesP(kenar,1,np.pi/180,50)
print(cizgi)

for i in cizgi:
    x1,y1,x2,y2=i[0]
    cv2.line(img,(x1,y1),(x2,y2),(255,0,0),2)

cv2.imshow("image",img)
cv2.waitKey(0)

[[[266 244 329 244]]

 [[137 242 162 242]]

 [[456 187 457 191]]

 ...

 [[164 248 164 247]]

 [[489 302 490 306]]

 [[229 115 246 115]]]


-1

In [1]:
import cv2
import numpy as np
cap=cv2.VideoCapture("cizgitakip3.mp4")

while True:
    ret,frame=cap.read()
    hsv=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    alt=np.array([34,68,94],np.uint8)
    ust=np.array([26,80,62],np.uint8) #alt üst ayarlar için color picker sitesinden tespite uygun renk için sınırlar belirleme

    mask=cv2.inRange(hsv,ust,alt)
    kenar=cv2.Canny(mask,50,250)
    cizgi=cv2.HoughLinesP(kenar,1,np.pi/180,50,maxLineGap=5)
    if cizgi is not None:
        for i in cizgi:
            x1,y1,x2,y2=i[0]
            cv2.line(frame,(x1,y1),(x2,y2),(0,255,0),5)
    else:
        pass# print("çizgi tespit edilemedi.")
    cv2.imshow("a",mask)
    cv2.imshow("f",frame)

    if ret==0:
        break
    if cv2.waitKey(20) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

In [1]:
#2 resim fark
import cv2
img1=cv2.imread("car.jpg")
img2=cv2.imread("car2.png")

fark=cv2.subtract(img1,img2)
b,g,r=cv2.split(fark)
print(fark)

cv2.imshow("fark",fark)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [6]:
#Haar Cascade ile Resim üzerinden yüz tespiti
import cv2
img=cv2.imread(("fce1.jpg"))

face=cv2.CascadeClassifier("frontalface.xml")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces=face.detectMultiScale(gray,1.3,4)

for x,y,w,h in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)

cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
#Video üzerinden yüz tespiti
import cv2

cap=cv2.VideoCapture("yuruyeninsanlar.mp4")
face=cv2.CascadeClassifier("frontalface.xml")

while True:
    ret,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)

    faces=face.detectMultiScale(gray,1.2,5)

    for x,y,w,h in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
    
    cv2.imshow("image",frame)

    if ret==0:
        break
    if cv2.waitKey(50) & 0xFF==ord("q"):
        break

cap.release()
cv2.destroyAllWindows()


In [4]:
#Webcam üzerinden yüz tespiti
cap=cv2.VideoCapture(0)
face=cv2.CascadeClassifier("frontalface.xml")

while True:
    ret,frame=cap.read()
    frame=cv2.flip(frame,1)
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)

    faces=face.detectMultiScale(gray,1.2,5)

    for x,y,w,h in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
    
    cv2.imshow("image",frame)

    if cv2.waitKey(50) & 0xFF==ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

In [8]:
#Haar Cascade ile Resim üzerinden göz tespiti
import cv2

img=cv2.imread("fce1.jpg")
face=cv2.CascadeClassifier("frontalface.xml")
eye=cv2.CascadeClassifier("haarscad_eye.xml")

gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces=face.detectMultiScale(gray,1.3,2)

for x,y,w,h in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)

    img2=img[y:y+h,x:x+h]
    gray2=gray[y:y+h,x:x+h]

    eyes=eye.detectMultiScale(gray2)
    
    for x1,y1,w1,h1 in eyes:
        cv2.rectangle(img2,(x1,y1),(x1+w1,y1+h1),(0,0,255),2)

cv2.imshow("1",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
#Video üzerinden göz tespiti
import cv2

cap=cv2.VideoCapture("yuruyeninsanlar.mp4")
face=cv2.CascadeClassifier("frontalface.xml")
eye=cv2.CascadeClassifier("haarscad_eye.xml")

while True:
    ret,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)

    faces=face.detectMultiScale(gray,1.3,2)

    for x,y,w,h in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)

        img2=frame[y:y+h,x:x+h]
        gray2=gray[y:y+h,x:x+h]

        eyes=eye.detectMultiScale(gray2)
    
        for x1,y1,w1,h1 in eyes:
            cv2.rectangle(img2,(x1,y1),(x1+w1,y1+h1),(0,0,255),2)

    cv2.imshow("1",frame)
    if cv2.waitKey(10)& 0xFF==ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

In [8]:
#Webcam üzerinden göz algılama
import cv2

cap=cv2.VideoCapture(0)
face=cv2.CascadeClassifier("frontalface.xml")
eye=cv2.CascadeClassifier("haarscad_eye.xml")

while True:
    ret,frame=cap.read()
    frame=cv2.flip(frame,1)
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)

    faces=face.detectMultiScale(gray,1.3,minNeighbors=5)

    for x,y,w,h in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)

        img2=frame[y:y+h,x:x+h]
        gray2=gray[y:y+h,x:x+h]

        eyes=eye.detectMultiScale(gray2,minNeighbors=5)
    
        for x1,y1,w1,h1 in eyes:
            cv2.rectangle(img2,(x1,y1),(x1+w1,y1+h1),(0,0,255),2)

    cv2.imshow("1",frame)
    if cv2.waitKey(10)& 0xFF==ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

In [13]:
#Resim üzerinden body algılama

import cv2
import numpy as np

img=cv2.imread("insan1.jpg")
body=cv2.CascadeClassifier("haarcascade_fullbody.xml")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

bodies=body.detectMultiScale(gray,1.1,3)

for x,y,w,h in bodies:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)

cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [14]:
#Video üzerinden body algılama

import cv2

cap=cv2.VideoCapture("yuruyeninsanlar.mp4")
body=cv2.CascadeClassifier("haarcascade_fullbody.xml")

while True:
    ret,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)

    bodies=body.detectMultiScale(gray,1.1,3)

    for x,y,w,h in bodies:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)

    cv2.imshow("img",frame)

    if cv2.waitKey(20) & 0xFF==ord("q"):
        break
cv2.destroyAllWindows()


In [17]:
import cv2
img=cv2.imread("trafficjam2.jpg")
car=cv2.CascadeClassifier("car.xml")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cars=car.detectMultiScale(gray,1.1,1)

for x,y,w,h in cars:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)

cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [2]:
import cv2
cap=cv2.VideoCapture("arabavideo.mp4")
car=cv2.CascadeClassifier("car.xml")
while True:
    ret,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cars=car.detectMultiScale(gray,1.1,1)

    for x,y,w,h in cars:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)

    cv2.imshow("img",frame)
    if cv2.waitKey(20) & 0xFF== ord("q"):
        break
cap.release()
cv2.destroyAllWindows()


In [2]:
#PYTESSERACT İLE RESİMDEN YAZI OKUMA

from PIL import Image
import pytesseract

img=Image.open("helloworld.png")
text=pytesseract.image_to_string(img,lang="eng")

print(text)

Hello World.



In [29]:
#Pytesseract ile plaka okuma
import cv2
import numpy as np
import pytesseract
import imutils


img=cv2.imread("plaka2.jpg")

gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
filter=cv2.bilateralFilter(gray,7,200,200)
kose=cv2.Canny(filter,40,200)

kontur,a=cv2.findContours(kose,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
cnt=imutils.grab_contours((kontur,a))
cnt=sorted(cnt,key=cv2.contourArea,reverse=True)[:10]

ekran=0
for i in cnt:
    eps=0.059*cv2.arcLength(i,True)
    aprx=cv2.approxPolyDP(i,eps,True)
    if len(aprx)==4:
        ekran=aprx
        break
# print(ekran)
maske=np.zeros(gray.shape,np.uint8)
newmask=cv2.drawContours(maske,[ekran],0,(255,255,255),-1)

yazi=cv2.bitwise_and(img,img,mask=maske)

(x,y)=np.where(maske==255)
(ustx,usty)=(np.min(x),np.min(y))
(altx,alty)=(np.max(x),np.max(y))
kirp=gray[ustx:altx+1,usty:alty+1]


# kernel = np.array([[-1, -1, -1],
#                    [-1, 9, -1],
#                    [-1, -1, -1]])

# sharpened = cv2.filter2D(kirp, -1, kernel)

# text=pytesseract.image_to_string(sharpened,lang="eng")
# cv2.imshow("1",img)
# cv2.imshow("2",gray)
# cv2.imshow("3",filter)
# cv2.imshow("4",kose)
# cv2.imshow("5",newmask)
cv2.imshow("6",yazi)
cv2.imshow("7",kirp)
# cv2.imshow("8",sharpened)
print(text)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [1]:
#rotate işlemleri
import numpy as np
import cv2

cap=cv2.VideoCapture(0)

while True:
    ret,frame=cap.read()
    frame=cv2.flip(frame,1)
    frame=cv2.rotate(frame,cv2.ROTATE_180)
    # frame=cv2.rotate(frame,cv2.ROTATE_90_CLOCKWISE)
    # frame=cv2.rotate(frame,cv2.ROTATE_90_COUNTERCLOCKWISE)


    cv2.imshow("img",frame)

    if cv2.waitKey(10) & 0xFF==ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

In [2]:
#Renk ile nesne tespiti

import cv2
import numpy as np
from collections import deque
#Buffer size ve pts değişkenleri, hareketin izlenmesi için bir buffer mekanizması oluşturmak için kullanılır.
buffer_size=16
pts=deque(maxlen=buffer_size) #koleksiyon veri yapısıdır ve hem baş hem de sondan veri ekleme veya çıkarma işlemleri yapılır.
#eğer deque'nün boyutu "buffer_size'a ulaşırsa, en eski veri otomatik olarak deque'nin başından çıkarılır ve yeni veri deque'nin sonuna eklenir,bu sayede boyut sabit kalır."
bluelower=(84,98,0)
blueupper=(170,200,200)

cap=cv2.VideoCapture(0)
cap.set(3,960) #genişliği 960 piksel olarak ayarlar.
cap.set(4,480) # yüksekliği 480 piksel olarak ayarlar.

while True:
    success,imgorginal=cap.read()
    imgorginal=cv2.flip(imgorginal,1)

    if success:
        blurred=cv2.GaussianBlur(imgorginal,(11,11),0) #görüntüyü yumuşatır ve gürültüyü azaltır
        hsv=cv2.cvtColor(blurred,cv2.COLOR_BGR2HSV)
        cv2.imshow("hsv penceresi",hsv)
        
        #inrange ile elde ettiğimiz maske, yüksekliği ve genişliği değiştirilebilen, genellikle düzensiz ve küçük beyaz bölgelerle dolu olabilir.
        #Erode, bu küçük beyaz bölgeleri küçültüp kaldırarak maskenin daha temiz bir versiyonunu elde etmemizi sağlar.Erozyon sonucunda renk aralığına
        #uyan bölgeler küçülür ve kenarları düzgünleşir.

        #Daha sonra genişletme işlemi(dilate) uygulanır.Bu, beyaz bölgeyi tekrar genişletir ve kenarları daha düzgün hale getirir.Erozyon ve genişletme işlemleri,
        #birbirini takip eden işlemler olarak kullanılır ve bu işlem sırası, maskenin daha tutarlı ve dengeli olmasını sağlar.
        mask=cv2.inRange(hsv,bluelower,blueupper) #bu renk aralığında kalan pikseller beyaz,diğerleri siyah olacak şekilde maske oluşur.
        mask=cv2.erode(mask,None,iterations=2)
        mask=cv2.dilate(mask,None,iterations=2)
        cv2.imshow("maskeli pencere",mask)


        
        
        """Maskeleme yapilan görüntünün konturlarinin bulunmasi,bu konturlardan en büyük olaninin belirlenmesi,minimum alan dikdörtgeni(bounding box) ve
        döndürme acisinin hesaplanmasi, bunlarin ekrana yazilmasi,döndürülmüs dikdörtgenin ve kontur merkezinin çizilmesi,ardindan çizilen merkezlerin arasinda
        bağlanti çizgileri çizilmesini içeren işlemler aşağidakilerdir. 
        """
        (contours,a)=cv2.findContours(mask.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
        #EXTERNAL,yalnızca dış konturları almak için kullanılır, CHA_AP_SIMPLE_, kontur noktalarını sadece başlangıç ve bitiş noktalarıyla temsil etmek için kullanılır.
        
        center=None #merkez değişkeni
        if len(contours)>0:
            c=max(contours,key=cv2.contourArea) #konturların içinden en büyük alanlı konturu seçer
            rect=cv2.minAreaRect(c) #seçilen konturun etrafına en küçük dikdörtgen kutuyu çizer.
            ((x,y),(width,height),rotation)=rect
            s="x:{}, y:{}, width:{}, height:{}".format(np.round(x),np.round(y),np.round(width),np.round(height),np.round(rotation))
            print(s)

            box=cv2.boxPoints(rect) # dikdörtgenin dört köşe noktasını alır.
            box=np.int64(box) #köşe noktalarını integer'a dönüştürür.

            M=cv2.moments(c) #kontor merkez hesaplama ve hemen ardından center değişkenine atama
            center=(int(M["m10"]/M["m00"]),int(M["m01"]/M["m00"]))
            cv2.drawContours(imgorginal,[box],0,(0,255,0),2) #dikdörtgenin kontürünü yeşil renkte çizer
            cv2.circle(imgorginal,center,5,(255,0,0)) #hesaplanan merkez noktasını mavi bir daire olarak çizer

        pts.append(center)
        for i in range(1,len(pts)):
            if pts[i-1] is None or pts[i] is None:continue
            cv2.line(imgorginal,pts[i-1],pts[i],(0,255,255),3)
            #Önceki merkez noktası ile şu anki merkez noktası arasında sarı renkte bir çizgi çizer.Bu, izlenen nesnenin hareketini görselleştirir ve
            # izlenen nesnenin geçmiş konumları arasında bir iz bırakır.
        cv2.imshow("original",imgorginal)

        





    if cv2.waitKey(1) & 0xFF==ord("q"):
        break

cap.release()
cv2.destroyAllWindows()

x:400.0, y:518.0, width:41.0, height:47.0
x:400.0, y:519.0, width:40.0, height:49.0
x:398.0, y:520.0, width:37.0, height:53.0
x:398.0, y:522.0, width:35.0, height:49.0
x:396.0, y:522.0, width:34.0, height:51.0
x:400.0, y:522.0, width:34.0, height:51.0
x:400.0, y:524.0, width:31.0, height:53.0
x:400.0, y:524.0, width:31.0, height:53.0
x:399.0, y:523.0, width:32.0, height:54.0
x:397.0, y:522.0, width:49.0, height:33.0
x:394.0, y:522.0, width:33.0, height:56.0
x:392.0, y:518.0, width:41.0, height:56.0
x:388.0, y:520.0, width:37.0, height:55.0
x:395.0, y:525.0, width:31.0, height:50.0
x:378.0, y:401.0, width:43.0, height:30.0
x:379.0, y:394.0, width:41.0, height:36.0
x:379.0, y:394.0, width:41.0, height:36.0
x:382.0, y:390.0, width:17.0, height:36.0
x:364.0, y:361.0, width:38.0, height:61.0
x:370.0, y:345.0, width:38.0, height:42.0
x:368.0, y:332.0, width:44.0, height:46.0
x:348.0, y:411.0, width:37.0, height:70.0
x:338.0, y:399.0, width:32.0, height:99.0
x:376.0, y:305.0, width:48.0, heig

In [3]:
#Open CV ile Maske tespiti

import cv2
cap=cv2.VideoCapture(0)
face_cascade=cv2.CascadeClassifier("frontalface.xml")
mouth_cascade=cv2.CascadeClassifier("mouth.xml")

while True:
    ret,frame=cap.read()
    frame=cv2.flip(frame,1)
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces=face_cascade.detectMultiScale(gray,1.1,7)

    if len(faces)==0:
        cv2.putText(frame,"Yuz tespit edilemedi.",(40,40),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2)
    else:
        for x,y,w,h in faces:
            cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2)
            roi_gray=gray[y:y+h,x:x+w]
            mouth=mouth_cascade.detectMultiScale(roi_gray,1.4,10)
            i=0
            if len(mouth)==0:
                cv2.putText(frame,"Maske var",(40,40),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2)
            else:
                for x1,y1,w1,h1 in mouth:
                    if i==0:
                        i=i+1
                        cv2.rectangle(frame,(x1+x,y1+y),(x1+x+w1,y1+y+h1),(255,0,0),3)
                    else:
                        pass
                    cv2.putText(frame,"Maske yok",(40,40),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2)

    cv2.imshow("a",frame)
    if cv2.waitKey(1) & 0xFF==ord("q"):
        break

cv2.destroyAllWindows()

In [4]:
#Trafikte geçen araç sayısını hesaplama with mog
import cv2
import numpy as np
cap=cv2.VideoCapture("trafficvideo2.mp4")
backsub=cv2.createBackgroundSubtractorMOG2(history=100,varThreshold=16,detectShadows=False)#arka planı temizleme işlemi 
c=0
previous_count = 0

width = int(cap.get(3))
height = int(cap.get(4))

print("Video Genişliği:", width)
print("Video Yüksekliği:", height)
while True:
    ret,frame=cap.read()
    if ret==1:
        fgmask=backsub.apply(frame)
        fgmask=cv2.erode(fgmask,None,iterations=2)
        fgmask=cv2.dilate(fgmask,None,iterations=2)

        cv2.line(frame,(0,280),(640,280),(0,255,0),2)
        cv2.line(frame,(0,350),(640,350),(0,255,0),2)


        contours,hiers=cv2.findContours(fgmask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
        try: 
            hiers=hiers[0]
        except: 
            hiers=[]


        for contour,hier in zip(contours,hiers):
            (x,y,w,h)=cv2.boundingRect(contour)
            if w>60 and h>60:
                cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
                if y>280 and y<350:
                    c=c+1
        if c>previous_count:
            previous_count=c

        font=cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(frame,"car "+str(previous_count),(90,100),font,2,(0,0,255),2,cv2.LINE_AA)
    
        cv2.imshow("vid",frame)
        cv2.imshow("vid2",fgmask)
        if cv2.waitKey(35) & 0xFF==ord("q"):
            break
    
    
cap.release()
cv2.destroyAllWindows()


Video Genişliği: 640
Video Yüksekliği: 360


In [9]:
#HOG
import cv2
from skimage.feature import hog
from skimage import exposure
img=cv2.imread("ataturk.jpg")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

_,hogimage=hog(gray,visualize=True)
rescaled=exposure.rescale_intensity(hogimage,in_range=(0,10))

cv2.imshow("orj",img)
cv2.imshow("hog",hogimage)
cv2.imshow("exp",rescaled)

cv2.waitKey(0)
cv2.destroyAllWindows()
